name: python

on: push

env:
  APIKEY: ${{secrets.APIKEY}}
  APIKEYAI: ${{secrets.APIKEYAI}}


jobs:
  test_env:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        APIKEYAI: ${{ secrets.APIKEYAI }} 
        APIKEY: ${{ secrets.APIKEY }} 
    - name: Debugging Secret
    run: echo "API-Key: ${{ secrets.APIKEYAI }}"
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
